/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/create_event.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send an event to PagerDuty
         * @description Your monitoring tools should send PagerDuty a trigger event to report a new problem, or update an ongoing problem, depending on the event type.
         */
        post: operations["createV1Event"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Image context */
        ImageContext: {
            /**
             * @description The type of context being attached to the incident (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            type: "ImageContext";
            /**
             * Format: url
             * @description The source of the image being attached to the incident. This image must be served via HTTPS.
             */
            src: string;
            /**
             * Format: url
             * @description Optional link for the image.
             */
            href?: string;
            /** @description Optional alternative text for the image. */
            alt?: string;
        };
        /** @description Link context */
        LinkContext: {
            /**
             * @description The type of context being attached to the incident (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            type: "LinkContext";
            /**
             * Format: url
             * @description The link being attached to the incident.
             */
            href: string;
            /** @description Optional information pertaining to this context link. */
            text?: string;
        };
    };
    responses: {
        /** @description The incident has been opened or updated. */
        Success: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description A short name for the error, or "success" if successful. */
                    status: string;
                    /** @description The key of the incident that will be affected by the request, if successful. */
                    incident_key?: string;
                    /** @description A description of the problem, or "Event processed" if successful. */
                    message?: string;
                };
            };
        };
        /** @description An error occurred on a request. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description A short name for the error. */
                    status: string;
                    /** @description A description of the problem. */
                    message: string;
                    /** @description An array of specific error messages. */
                    errors?: string[];
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createV1Event: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The GUID of one of your "Generic API" services. This is the "Integration Key" listed on a Generic API's service detail page. */
                    service_key: string;
                    /**
                     * @description The type of event. Can be `trigger`, `acknowledge` or `resolve`.
                     * @enum {string}
                     */
                    event_type: "trigger" | "acknowledge" | "resolve";
                    /** @description Identifies the incident to `trigger`, `acknowledge`, or `resolve`. Required unless the `event_type` is `trigger`. */
                    incident_key?: string;
                    /** @description Text that will appear in the incident's log associated with this event. Required for `trigger` events. */
                    description?: string;
                    /** @description An arbitrary JSON object containing any data you'd like included in the incident log. */
                    details?: Record<string, never>;
                    /** @description The name of the monitoring client that is triggering this event. (This field is only used for `trigger` events.) */
                    client?: string;
                    /**
                     * Format: url
                     * @description The URL of the monitoring client that is triggering this event. (This field is only used for `trigger` events.)
                     */
                    client_url?: string;
                    /** @description Contexts to be included with the incident trigger such as links to graphs or images. (This field is only used for `trigger` events.) */
                    contexts?: (components["schemas"]["LinkContext"] | components["schemas"]["ImageContext"])[];
                };
            };
        };
        responses: {
            200: components["responses"]["Success"];
            /** @description Invalid event format (i.e. JSON parse error) or incorrect event structure */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit reached (too many Events API requests) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "5XX": components["responses"]["Error"];
        };
    };
}
