/*
 * Generated on Sat, 31 Jan 2026 21:50:18 GMT
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/change/enqueue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send change events to the PagerDuty Events API
         * @description Change Events API enables you to send informational events about recent changes such as code deploys and system config changes from any system that can make an outbound HTTP connection.
         *     These events do not create incidents and do not send notifications; they are shown in context with incidents on the same PagerDuty service.
         */
        post: operations["createChangeEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enqueue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send an event to PagerDuty
         * @description Your monitoring tools should send PagerDuty a trigger event to report a new problem, or update an ongoing problem, depending on the event type.
         */
        post: operations["createV2Event"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Images to be displayed on the alert and/or corresponding incident. */
        Images: {
            /**
             * Format: url
             * @description The source of the image being attached to the incident or alert. This image must be served via HTTPS.
             */
            src: string;
            /**
             * Format: url
             * @description Optional link for the image.
             */
            href?: string;
            /** @description Optional alternative text for the image. */
            alt?: string;
        }[];
        /** @description Links to be shown on the alert and/or corresponding incident. */
        Links: {
            /**
             * Format: url
             * @description The link being attached to an incident or alert.
             */
            href: string;
            /** @description Optional information pertaining to this context link. */
            text?: string;
        }[];
        /** @description Fields adding additional context about the location, impact, and character of the PagerDuty event. */
        Payload: {
            /** @description A brief text summary of the event, used to generate the summaries/titles of any associated alerts. */
            summary: string;
            /**
             * Format: date-time
             * @description The time at which the emitting tool detected or generated the event.
             */
            timestamp?: string;
            /**
             * @description The perceived severity of the status the event is describing withrespect to the affected system.
             * @enum {unknown}
             */
            severity: "critical" | "warning" | "error" | "info";
            /** @description The unique location of the affected system, preferably a hostname or FQDN. */
            source: string;
            /** @description Component of the source machine that is responsible for the event. */
            component?: string;
            /** @description Logical grouping of components of a service. */
            group?: string;
            /** @description The class/type of the event. */
            class?: string;
            /** @description Additional details about the event and affected system. */
            custom_details?: Record<string, never>;
        };
        /** @description Fields adding additional context about the location, impact, and character of the PagerDuty event. */
        ChangeEventPayload: {
            /** @description A brief text summary of the event, used to generate the summaries/titles of any associated alerts. */
            summary: string;
            /**
             * Format: date-time
             * @description The time at which the emitting tool detected or generated the event.
             */
            timestamp?: string;
            /** @description The unique location of the affected system, preferably a hostname or FQDN. */
            source?: string;
            /** @description Additional details about the event and affected system. */
            custom_details?: Record<string, never>;
        };
    };
    responses: {
        /** @description An alert has been created or updated. */
        Success: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Returns "success" if successful, or a short error message in case of a failure. */
                    status: string;
                    /** @description The key used to correlate triggers, acknowledges, and resolves for the same alert. */
                    dedup_key?: string;
                    /** @description A description of the problem, or "Event processed" if successful. */
                    message?: string;
                };
            };
        };
        /** @description An error occurred on a request. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description A short name for the error. */
                    status: string;
                    /** @description A description of the problem. */
                    message: string;
                    /** @description An array of specific error messages. */
                    errors?: string[];
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createChangeEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    payload: components["schemas"]["ChangeEventPayload"];
                    /** @description The GUID of one of your Events API V2 integrations. This is the "Integration Key" listed on the Events API V2 integration's detail page. */
                    routing_key: string;
                    links?: components["schemas"]["Links"];
                    images?: components["schemas"]["Images"];
                };
            };
        };
        responses: {
            202: components["responses"]["Success"];
            /** @description #/components/responses/ArgumentError */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description #/components/responses/TooManyRequests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "5XX": components["responses"]["Error"];
        };
    };
    createV2Event: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    payload?: components["schemas"]["Payload"];
                    /** @description The GUID of one of your Events API V2 integrations. This is the "Integration Key" listed on the Events API V2 integration's detail page. */
                    routing_key: string;
                    /**
                     * @description The type of event. Can be `trigger`, `acknowledge` or `resolve`.
                     * @enum {unknown}
                     */
                    event_action: "trigger" | "acknowledge" | "resolve";
                    /** @description Identifies the alert to `trigger`, `acknowledge`, or `resolve`. Required unless the `event_type` is `trigger`. */
                    dedup_key?: string;
                    /** @description The name of the monitoring client that is triggering this event. (This field is only used for `trigger` events.) */
                    client?: string;
                    /**
                     * Format: url
                     * @description The URL of the monitoring client that is triggering this event. (This field is only used for `trigger` events.)
                     */
                    client_url?: string;
                    links?: components["schemas"]["Links"];
                    images?: components["schemas"]["Images"];
                };
            };
        };
        responses: {
            202: components["responses"]["Success"];
            /** @description #/components/responses/ArgumentError */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description #/components/responses/TooManyRequests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "5XX": components["responses"]["Error"];
        };
    };
}
